/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    edifici: Edifici;
    sottosistemi: Sottosistemi;
    localita: Localita;
    comuni: Comuni;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edifici".
 */
export interface Edifici {
  id: string;
  localita?: (string | null) | Localita;
  sezione_localita?: string | null;
  geolocalizzazione?: {
    /**
     * @minItems 2
     * @maxItems 2
     */
    coordinate?: [number, number] | null;
    altitudine?: number | null;
    precision?: number | null;
  };
  anagrafica?:
    | {
        anno?: string | null;
        particella?: string | null;
        subalterno?: string | null;
        accessibilita?: ('sentiero' | 'vicolo pedonale' | 'strada carrabile' | 'strada in terra battuta')[] | null;
        unita?:
          | {
              piani?: number | null;
              sottotetto?: boolean | null;
              seminterrato?: boolean | null;
              piano_interrato?: boolean | null;
              id?: string | null;
            }[]
          | null;
        stato_utilizzo?:
          | ('uso permanente' | 'uso temporaneo' | 'disuso' | 'disuso - rudere' | 'non rilevabile' | 'non presente')
          | null;
        stato_utilizzo_secondario?:
          | ('uso permanente' | 'uso temporaneo' | 'disuso' | 'disuso - rudere' | 'non rilevabile' | 'non presente')
          | null;
        stato_conservazione?:
          | (
              | 'fenomeni di degrado diffusi'
              | 'fenomeni di degrado superficiali'
              | 'modifiche sostanziali caratteri tradizionali'
              | 'non presente'
              | 'non rilevabile'
              | 'perdita funzionalità'
              | 'senza fenomeni di degrado'
              | 'nd'
            )[]
          | null;
        destinazioni_uso?:
          | {
              nome?: string | null;
              tag_storico?:
                | (
                    | 'cantina'
                    | 'cantina d'
                    | 'casa'
                    | 'casa abb'
                    | 'casa cantoniera'
                    | 'casa coadiutorale'
                    | 'casa dir'
                    | 'casa guardiano'
                    | 'casa parro'
                    | 'casa uffici postali'
                    | 'casello'
                    | 'caserma'
                    | 'casolare'
                    | 'casolare a'
                    | 'casolare d'
                    | 'castagneto'
                    | 'cc'
                    | 'ceppo nudo'
                    | 'coltivo'
                    | 'dogana'
                    | 'ed religioso'
                    | 'fabbrica'
                    | 'fienile'
                    | 'ls'
                    | 'lt'
                    | 'lt abb'
                    | 'mulino'
                    | 'nd'
                    | 'p cantina'
                    | 'p casa'
                    | 'p cc'
                    | 'p fienile'
                    | 'p lt'
                    | 'p sf'
                    | 'p stalla'
                    | 'pasc alpe'
                    | 'pascolo'
                    | 'prato'
                    | 'sasso n'
                    | 'sf'
                    | 'stalla'
                    | 'zappativo'
                    | 'zerbo'
                    | 'PRATO'
                    | 'NP'
                    | 'URBANO'
                    | 'FA URBANO'
                    | 'PFA RURALE'
                    | 'FA RURALE'
                  )
                | null;
              tag_moderno?:
                | (
                    | 'commerciale'
                    | 'luogo di culto'
                    | 'multifunzione'
                    | 'non rilevabile'
                    | 'produttivo'
                    | 'produttivo rurale'
                    | 'residenziale'
                    | 'servizio'
                    | 'verde'
                    | 'servizio accessorio'
                    | 'nd'
                  )
                | null;
              id?: string | null;
            }[]
          | null;
        stato?: ('presente' | 'non presente' | 'non disponibile' | 'parziale') | null;
        id?: string | null;
      }[]
    | null;
  analisi_strutturale?:
    | {
        componente?: ('verticali' | 'orizzontali' | 'coperture' | 'fondazioni') | null;
        materiali?:
          | (
              | 'calcestruzzo armato'
              | 'laterizi'
              | 'legno'
              | 'non rilevabile'
              | 'pietra a secco'
              | 'pietra con legante'
              | 'non presente'
              | 'pietra'
              | 'materiale metallico'
              | 'materiale plastico'
              | 'altro'
            )[]
          | null;
        tecnica_costruttiva?:
          | (
              | 'a telaio '
              | 'incardinato'
              | 'incardinato + basamento e/o parziale rivestimento in pietra'
              | 'muri portanti'
              | 'non rilevabile'
              | 'a telaio'
              | 'volte'
              | 'altra tecnica'
              | 'non presente'
              | 'tecnica moderna'
              | 'tecnica tradizionale'
            )
          | null;
        stato_conservazione?:
          | (
              | 'fenomeni di degrado diffusi'
              | 'fenomeni di degrado superficiali'
              | 'modifiche sostanziali caratteri tradizionali'
              | 'non presente'
              | 'non rilevabile'
              | 'perdita funzionalità'
              | 'senza fenomeni di degrado'
              | 'nd'
            )
          | null;
        fenomeni_degrado?:
          | (
              | 'corrosione elementi metallici'
              | 'corrosione componenti metallici'
              | 'deposito superficiale'
              | 'erosione / deformazione elementi strutturali lignei'
              | 'erosione elementi lignei strutturali'
              | 'erosione giunti di malta'
              | 'fessurazioni'
              | 'mancanza componenti strutturali'
              | 'mancanza elementi puntuali'
              | 'mancanza elementi singoli'
              | 'mancanza elementi strutturali puntuali (conci lapidei, elementi lignei)'
              | 'mancanza elementi strutturali'
              | 'marcescenza componenti strutturali lignee'
              | 'marcescenza elementi lignei strutturali'
              | 'patina biologica'
              | 'rappezzi cementizi'
              | 'umidità di risalita'
              | 'vegetazione infestante'
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  analisi_componenti_architettoniche?:
    | {
        fronte?: ('sud' | 'nord' | 'est' | 'ovest' | 'generale') | null;
        componente?: ('finiture esterne' | 'infissi esterni' | 'apparati decorativi' | 'collegamenti esterni') | null;
        tipologia?:
          | (
              | 'intonaco_fine'
              | 'intonaco_rustico'
              | 'intonaco_tintura'
              | 'non presente'
              | 'rivestiment in pietra (basamento)'
              | 'rivestimento in legno'
              | 'porte'
              | 'portone'
              | 'grate'
              | 'box auto'
              | 'portefinestre'
              | 'finestre'
              | 'persiane / scuri'
              | 'tapparelle'
              | 'angolari in conci lapidei'
              | 'architravi lapidei'
              | 'architravi lignei'
              | 'cornici lapidee o tinte'
              | 'dipinti - affreschi'
              | 'finestre a sguincio'
              | 'iscrizioni storiche'
              | 'marcapiano'
              | 'ballatoio'
              | 'loggia'
              | 'scale'
              | 'sottopassaggio'
              | 'balcone'
            )[]
          | null;
        materiali?:
          | (
              | 'malta cementizia (grigia)'
              | 'malta di calce (bianca - aerea)'
              | 'malta di calce (giallastra - idraulica)'
              | 'legno'
              | 'materiale plastico'
              | 'metallo'
              | 'pietra'
              | 'calcestruzzo armato'
            )[]
          | null;
        stato_conservazione?:
          | (
              | 'fenomeni di degrado diffusi'
              | 'fenomeni di degrado superficiali'
              | 'modifiche sostanziali caratteri tradizionali'
              | 'non presente'
              | 'non rilevabile'
              | 'perdita funzionalità'
              | 'senza fenomeni di degrado'
              | 'nd'
            )
          | null;
        fenomeni_degrado?:
          | (
              | 'colature'
              | 'corrosione elementi metallici'
              | 'deposito superficiale'
              | 'erosione malta di rivestimento'
              | 'disgregazione malta di rivestimento'
              | 'erosione giunti di malta'
              | 'fessurazioni'
              | 'lacuna malta di rivestimento'
              | 'marcescenza legno'
              | 'patina biologica'
              | 'rappezzi cementizi'
              | 'umidità di risalita'
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  altro?: {
    pavimentazioni_esterne?: ('ceramica' | 'pietra' | 'strada carrabile' | 'terra battuta')[] | null;
    smaltimento_acqua?: ('metallo' | 'legno' | 'non rilevabile' | 'non presente')[] | null;
    impiantistica?: ('elettrico' | 'gas' | 'idrico sanitario' | 'idrico' | 'non presente' | 'non rilevabile')[] | null;
    opere_provvisionali?:
      | ('scatola muraria (tiranti, puntellature, centine)' | 'coperture provvisorie' | 'altro')[]
      | null;
    vincoli_tutele?: ('I1' | 'I2' | 'I3' | 'I4' | 'I5' | 'LOCALE' | 'REGIONALE' | 'NAZIONALE')[] | null;
    caratteri_storico_culturali?:
      | (
          | 'cardèn (struttura in legno incardinata)'
          | 'casèl (conservazione latte)'
          | 'crapèna - tècc (fienile)'
          | 'crotto'
          | 'edificio rurale in pietra (stalla / fienile o gre)'
          | 'fienile'
          | 'grè (essicatoio castagne)'
          | 'pigna'
          | 'pilastri basamento'
          | 'scigugna / culdera (produzione casearia)'
          | 'solè (parziale cardèn a valle)'
          | 'stalla fienile'
          | 'stua interna'
          | 'tabìa (stalla / fienile con pilastri / tamponatura in legno)'
        )[]
      | null;
  };
  dati_lavoro?: {
    imu_2021?:
      | {
          code?: string | null;
          id?: string | null;
        }[]
      | null;
    tari_2021?: string | null;
    punto_gis?: string | null;
    altre_note?: string | null;
    informazioni_aggiuntive?: string | null;
  };
  immagini?: (string | Media)[] | null;
  immagini_url?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "localita".
 */
export interface Localita {
  id: string;
  name: string;
  sottosistemi?: (string | Sottosistemi)[] | null;
  slm: number;
  codice_localita: number;
  abitanti_residenti_2022?: number | null;
  accessibilita_principale?: ('sentiero' | 'mulattiera' | 'strada asfaltata' | 'strada sterrata')[] | null;
  viabilita_interna_tipi?: ('pedonale' | 'veicolare')[] | null;
  viabilita_interna_materiali?:
    | (
        | 'acciottolato'
        | 'acciottolato a coltello con traversine trasversali'
        | 'pavimentata'
        | 'piode'
        | 'terra battuta'
      )[]
    | null;
  reti_e_servizi?:
    | (
        | 'rete idrica'
        | 'rete elettrica'
        | 'illuminazione pubblica'
        | 'rete telefonica'
        | 'telefono pubblico'
        | 'cimitero'
        | 'bar trattoria'
        | 'pensione'
      )[]
    | null;
  elementi_urbanistici?:
    | ('fontana' | 'lavatoio' | 'panche' | 'passaggi coperti' | 'soste' | 'vasca in pietra monolitica')
    | null;
  dati_1988?:
    | {
        accessibilita_principale?: ('sentiero' | 'mulattiera' | 'strada asfaltata' | 'strada sterrata')[] | null;
        viabilita_interna_tipi?: ('pedonale' | 'veicolare')[] | null;
        viabilita_interna_materiali?:
          | (
              | 'acciottolato'
              | 'acciottolato a coltello con traversine trasversali'
              | 'pavimentata'
              | 'piode'
              | 'terra battuta'
            )[]
          | null;
        reti_e_servizi?:
          | (
              | 'rete idrica'
              | 'rete elettrica'
              | 'illuminazione pubblica'
              | 'rete telefonica'
              | 'telefono pubblico'
              | 'cimitero'
              | 'bar trattoria'
              | 'pensione'
            )[]
          | null;
        uso_pre?: ('abbandono' | 'discontinuo' | 'permanente' | 'stagionale') | null;
        uso?: ('abbandono' | 'discontinuo' | 'permanente' | 'stagionale') | null;
        stato_conservazione?:
          | (
              | 'complesso in discrete condizioni con interventi di recupero non corretti'
              | 'complesso in discrete condizioni di conservazione'
              | 'complesso in pessime condizioni di conservazione'
              | 'senza gravi alterazioni ma in stato di abbandono e carente di manutenzione'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  hide?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sottosistemi".
 */
export interface Sottosistemi {
  id: string;
  name: string;
  comune: string | Comuni;
  sottosistema_storico?: (string | null) | Sottosistemi;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comuni".
 */
export interface Comuni {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}